---
general:
  buildTool: 'mta'

stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true

  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false

  Release:
    cloudFoundryDeploy: true

steps:
  npmExecuteLint:
    failOnError: true

  mtaBuild:
    platform: 'CF'
 
  cloudFoundryDeploy:
    cfCredentialsId: cf-credentials
    apiEndpoint: 'https://api.cf.eu10-004.hana.ondemand.com'
    org: tfe-saas-dev-test
    space: dev
    mtaDeployParameters: '-f --version-rule ALL'
    mtaExtensionDescriptor: './configs/deployment/tfe.mtaext'
    mtaExtensionCredentials: 
      susaas-sb-credentials: susaas-sb-credentials

# tmsUpload:  # only relevant once you finish the SAP Cloud Transport Management Expert Scope chapter
#   nodeName: 'QA'
#   credentialsId: 'tms'
#   customDescription: 'TMS Upload'